[package]
name = "kloak"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33.3"
evdev = "0.11.0"
rand = "0.8.4"
rand_chacha= "0.3.1"
